Add calico configuration support
dcos-terraform/terraform-null-dcos-install-remote-exec pull request #12
Opened 2020-01-02 10:42 UTC by mainred

Add calico configurations into terraform and make several small fixes. 

fix: [DCOS-62550](https://jira.mesosphere.com/browse/DCOS-62550) integration calico configuration into terraform

2020-01-06 11:33 UTC, wavesoft submitted a review, later dismissed
LGTM! 👍

2020-01-15 14:01 UTC, fatz requested changes
the minimum core version should be `version = "~> 0.2.12"` as previous releases do not support the new vars

2020-01-16 07:02 UTC, mainred commented on main.tf
> +  version = "~> 0.2.12"
`dcos-terraform/dcos-core/template` will cut a new release to include calico configurations

2020-01-16 17:00 UTC, fatz requested changes
please have a look at my comment. The var gets forwarded twice.

I think it will run anyways but lets keep this clean

2020-01-16 17:00 UTC, fatz commented on main.tf
> +  dcos_calico_vxlan_port                       = "${var.dcos_calico_vxlan_port}"
`dcos_calico_vxlan_port` is duplicated

2020-01-18 13:44 UTC, mainred commented on main.tf
> +  dcos_calico_vxlan_port                       = "${var.dcos_calico_vxlan_port}"
Done, thanks. 
Can we test these changes in our local env?

2020-01-20 08:31 UTC, fatz commented on main.tf
> +  dcos_calico_vxlan_port                       = "${var.dcos_calico_vxlan_port}"
yes but you have to use our forked terraform build which supports `Terraformfile` 

https://github.com/fatz/terraform/releases/tag/v0.11.14-mesosphere the feature is documented here https://github.com/hashicorp/terraform/pull/20229

With that you can overwrite module sources.

This is also used by Jenkins. I've used this `Terraformfile` to test your changes

```json
{
  "dcos-terraform/dcos/aws": {
    "source": "git::https://github.com/mainred/terraform-aws-dcos.git?ref=add-calico-configurations"
  },
  "dcos-terraform/dcos-install-remote-exec/null": {
    "source": "git::https://github.com/mainred/terraform-null-dcos-install-remote-exec.git?ref=add-calico-configurations"
  },
  "dcos-terraform/dcos-core/template": {
    "source": "git::https://github.com/mainred/terraform-template-dcos-core.git?ref=add-calico-configurations"
  }
}
```

2020-01-23 13:26 UTC, fatz approved these changes

2020-01-23 13:28 UTC, merged