Add enable_mesos_input_plugin config option
dcos-terraform/terraform-null-dcos-install-remote-exec pull request #4
Opened 2019-01-17 21:22 UTC by gracedo

https://jira.mesosphere.com/browse/DCOS-47301
Adds the enable_mesos_input_plugin config option.

Terraform Core PR: dcos-terraform/terraform-template-dcos-core#2
DCOS PR: dcos/dcos#4222

2019-01-23 21:46 UTC, geekbass requested changes
Code LGTM outside of needing to update the variable name and description. Please update to:

dcos_enable_mesos_input_plugin with description "Indicates whether to enable Telegraf's Mesos input plugin to collect Mesos metrics from Mesos masters and agents. Options: `true` or `false` (optional)"

Adding @fatz as second pair of eyes.

2019-01-23 21:46 UTC, geekbass commented on main.tf
> -  source  = "dcos-terraform/dcos-install-bootstrap-remote-exec/null"
Please set this source back prior to merge.

2019-01-23 21:46 UTC, geekbass commented on main.tf
> +  // version = "~> 0.1.0"
Please set version back prior to merge.

2019-01-28 19:33 UTC, bernadinm approved these changes
LGTM!
When Jenkins is back up, let's rerun the job before merging if possible.

2019-01-28 21:14 UTC, geekbass approved these changes

2019-01-31 21:31 UTC, bernadinm commented
manually ran the test. Here is the output, good to merge:
```
$ terraform fmt
$ terraform validate --check-variables=false
$ docker run -ti -v$(pwd):/a --entrypoint /usr/bin/terraform-docs fatz/terraform-jenkins md /a | tr -d '\r' > README.md
$ git status
On branch gracedo/enable_mesos_input_plugin_config_option
Your branch is up to date with 'origin/gracedo/enable_mesos_input_plugin_config_option'.```

2019-01-31 21:33 UTC, merged